services:
  - type: web
    name: reuniao-nicopel-frontend
    env: node
    buildCommand: "npm install -g vite && npm install && npm run build"
    startCommand: "npx vite preview --port $PORT"
    publishPath: "dist"
    autoDeploy: true
