services:
  - type: web
    name: sala-reuniao-frontend
    env: node
    plan: free
    buildCommand: |
      rm -rf node_modules package-lock.json
      npm install
      npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: VITE_DATABASE_URL
        value: "postgresql://neondb_owner:npg_eli6x8japnmP@ep-fragrant-heart-a4f388d0-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require"
    autoDeploy: true
