# render.yaml
services:
  - type: web
    name: reuniao-nicopel-frontend
    env: node
    region: sa-east-1  # Região do Brasil (opcional)
    nodeVersion: 20.13.1  # Versão compatível com seu projeto
    buildCommand: "npm install && npm run build"
    startCommand: "serve -s dist -l $PORT"  # Serve para aplicação estática
    publishPath: "/dist"
    staticSite: true  # Indica que é um site estático
    autoDeploy: true